worker_processes 1;
events { worker_connections 1024; }
http {
  server {
    listen 80;
    location / {
      proxy_pass http://ditto-gateway:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      auth_basic "Ditto";
      auth_basic_user_file /etc/nginx/ditto.htpasswd;
      proxy_set_header x-ditto-pre-authenticated "ditto:$remote_user";
    }
  }
}
